/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/uploads/sign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tools/{name}/invoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["invoke"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/passes/portal-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["portalSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/passes/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["checkout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lookup/rdw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rdw"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dossiers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["save"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agent/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["chat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agent/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["chatStream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/voertuig/{plate}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/voertuig/{plate}/marktaanbod": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMarktaanbod"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/voertuig/{plate}/kosten": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getKosten"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete: operations["deleteMe"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/passes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/credits/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dossiers/{plate}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UploadRequest: {
            /** @description Chat session id this upload is attached to */
            sessionId: string;
            /** @description MIME type. Allowed: image/jpeg, image/png, image/webp, image/heic, application/pdf. */
            contentType: string;
        };
        UploadResponse: {
            /** @description V4 signed PUT URL. Client uploads bytes here with `Content-Type` matching the requested type. */
            uploadUrl: string;
            /** @description Server-computed gs:// path. Pass this back to the agent in chat messages. */
            gsPath: string;
            contentType: string;
            /** Format: date-time */
            expiresAt: string;
        };
        JsonNode: unknown;
        ToolInvokeRequest: {
            /** @description Tool-specific arguments as a JSON object */
            args: components["schemas"]["JsonNode"];
            sessionId?: string | null;
            passId?: string | null;
        };
        ToolInvokeResponse: {
            name: string;
            data?: null;
            /** Format: int32 */
            creditCost: number;
            cacheHit: boolean;
        };
        PortalRequest: {
            /** @description URL Stripe Customer Portal redirects to on Back. */
            returnTo: string;
        };
        PortalResponse: {
            sessionUrl: string;
        };
        CheckoutRequest: {
            /**
             * @description SINGLE | COMPARE3 | POWER10
             * @enum {string}
             */
            pack: "SINGLE" | "COMPARE3" | "POWER10";
            /** @description Bare base URL Stripe redirects to after checkout (e.g. https://app.example.com/dashboard). Agent appends ?paid=ok|cancel. */
            returnTo: string;
            /** @description Existing pass id to top-up; omit to create a new pass */
            bindToPassId?: string | null;
            /** @description UI language for the Stripe-hosted Checkout page (nl | en). Defaults to nl. */
            lang?: string | null;
        };
        CheckoutResponse: {
            sessionId: string;
            sessionUrl: string;
        };
        RdwLookupRequest: {
            plate: string;
        };
        RdwVehicleSummary: {
            /** @description Normalized plate without separators */
            kenteken: string;
            found: boolean;
            make?: string | null;
            model?: string | null;
            /** Format: date */
            firstRegistration?: string | null;
            /** Format: date */
            firstNlRegistration?: string | null;
            imported: boolean;
            /** Format: date */
            apkValidUntil?: string | null;
            apkValid: boolean;
            openRecall: boolean;
            liabilityInsured: boolean;
            exported: boolean;
            taxi: boolean;
            energyLabel?: string | null;
        };
        SaveRequest: {
            plate: string;
            merk?: string | null;
            model?: string | null;
            year?: string | null;
        };
        SavedDossierView: {
            plate: string;
            merk?: string | null;
            model?: string | null;
            year?: string | null;
            savedAt?: string | null;
            lastViewedAt?: string | null;
        };
        ChatRequest: {
            /** @description User message (max 4 000 chars). */
            message: string;
            /** @description Existing session id; if absent the agent creates one. */
            sessionId?: string | null;
            /** @description Dutch licence plate. When set on the first turn, the agent receives the RDW dossier as context. */
            plateContext?: string | null;
            /** @description UI language hint (nl | en). Drives the agent's reply voice. Defaults to nl. */
            lang?: string | null;
        };
        Algemeen: {
            merk?: string;
            model?: string;
            voertuigsoort?: string;
            inrichting?: string;
            eersteKleur?: string;
            tweedeKleur?: string;
            /** Format: int32 */
            nieuwprijsEuro?: number;
            /** Format: int32 */
            brutoBpmEuro?: number;
            /** Format: int32 */
            aantalDeuren?: number;
            /** Format: int32 */
            aantalZitplaatsen?: number;
            /** Format: date */
            datumEersteToelating?: string;
            /** Format: date */
            datumEersteNlRegistratie?: string;
            /** Format: date */
            datumTenaamstelling?: string;
            importauto?: boolean;
            europeseVoertuigcategorie?: string;
            typegoedkeuringsnummer?: string;
            variant?: string;
            uitvoering?: string;
        };
        ApkInspection: {
            /** Format: date */
            datum?: string;
            tijd?: string;
            soort?: string;
            resultaat?: string;
            aandachtspunten?: string[];
        };
        Carrosserie: {
            /** Format: int32 */
            lengteCm?: number;
            /** Format: int32 */
            breedteCm?: number;
            /** Format: int32 */
            hoogteCm?: number;
            /** Format: int32 */
            wielbasisCm?: number;
            /** Format: int32 */
            aantalWielen?: number;
            /** Format: int32 */
            massaLedigKg?: number;
            /** Format: int32 */
            massaRijklaarKg?: number;
            /** Format: int32 */
            toegestaneMaximumMassaKg?: number;
            /** Format: int32 */
            maxTrekkenOngeremdKg?: number;
            /** Format: int32 */
            maxTrekkenGeremdKg?: number;
            /** Format: double */
            vermogenMassarijklaar?: number;
        };
        MotorMilieu: {
            brandstof?: string;
            /** Format: int32 */
            aantalCilinders?: number;
            /** Format: int32 */
            cilinderinhoudCc?: number;
            /** Format: double */
            vermogenKw?: number;
            /** Format: int32 */
            vermogenPk?: number;
            /** Format: double */
            verbruikStad?: number;
            /** Format: double */
            verbruikSnelweg?: number;
            /** Format: double */
            verbruikGecombineerd?: number;
            /** Format: int32 */
            co2GecombineerdGperKm?: number;
            zuinigheidslabel?: string;
            uitlaatemissieniveau?: string;
            emissiecode?: string;
            hybrideKlasse?: string;
            /** Format: int32 */
            geluidsniveauRijdend?: number;
            /** Format: int32 */
            geluidsniveauStationair?: number;
        };
        RdwVehicleDetail: {
            kenteken: string;
            found: boolean;
            algemeen?: components["schemas"]["Algemeen"];
            motorMilieu?: components["schemas"]["MotorMilieu"];
            carrosserie?: components["schemas"]["Carrosserie"];
            status?: components["schemas"]["Status"];
            apkHistorie: components["schemas"]["ApkInspection"][];
        };
        Status: {
            /** Format: date */
            apkGeldigTot?: string;
            apkGeldig?: boolean;
            wamVerzekerd?: boolean;
            openstaandeTerugroepactie?: boolean;
            wokStatus?: boolean;
            wokToelichting?: string;
            taxi?: boolean;
            exported?: boolean;
            tenaamstellenMogelijk?: boolean;
            tellerstandoordeel?: string;
            /** Format: int32 */
            laatsteRegistratieTellerstandJaar?: number;
        };
        MarktaanbodListing: {
            title: string;
            url: string;
            /** @description Hostname of the listing source - marktplaats.nl, autoscout24.nl, etc. */
            source: string;
            snippet?: string | null;
            /** @description Parsed price hint (e.g. "€ 4.950"). null when the regex couldn't safely extract one - UI links out without a price. */
            priceHint?: string | null;
        };
        MarktaanbodResponse: {
            listings: components["schemas"]["MarktaanbodListing"][];
            /** @description When the underlying Google Custom Search call ran. Helps UI show a freshness pill. */
            fetchedAt?: string | null;
        };
        Assumptions: {
            /** Format: int32 */
            kilometersPerYear: number;
            /** Format: double */
            fuelPriceEurPerLiter: number;
            fuelPriceLabel: string;
        };
        MonthlyCosts: {
            kenteken: string;
            province: string;
            mrb?: components["schemas"]["Mrb"];
            fuel?: components["schemas"]["Range"];
            insurance?: components["schemas"]["Range"];
            maintenance?: components["schemas"]["Range"];
            apkReservering?: components["schemas"]["Range"];
            total: components["schemas"]["Range"];
            assumptions: components["schemas"]["Assumptions"];
        };
        Mrb: {
            /** Format: int32 */
            baseQuarterEur: number;
            /** Format: int32 */
            fuelSurchargeQuarterEur: number;
            /** Format: int32 */
            provincialOpcentenPercent: number;
            /** Format: int32 */
            totalQuarterEur: number;
            /** Format: int32 */
            monthEur: number;
            fuelClass: string;
            /** Format: int32 */
            weightKg: number;
        };
        Range: {
            /** Format: int32 */
            lowEur: number;
            /** Format: int32 */
            highEur: number;
            /** Format: int32 */
            midpointEur: number;
        };
        AiAnalysis: {
            samenvatting: string;
            marktwaarde: components["schemas"]["Marktwaarde"];
            vergelijkingHuidigeModellen: string;
            nederlandseBelastingvoordelen: string;
            milieuzonesEnBans: string;
            concurrentenOemBrands: string[];
            aandachtspuntenBijAankoop: string[];
            voordelen: string[];
            nadelen: string[];
            overigeOpmerkingen: string;
            /** Format: date-time */
            generatedAt: string;
        };
        Marktwaarde: {
            schattingEur: string;
            toelichting: string;
        };
        MeResponse: {
            uid: string;
            email?: string | null;
            emailVerified: boolean;
            /** @description free | pass | pro | power */
            tier: string;
        };
        Parameter: {
            name?: string;
            type?: string;
            description?: string;
            required?: boolean;
        };
        ToolSpec: {
            name?: string;
            description?: string;
            /** Format: int32 */
            creditCost?: number;
            parameters?: components["schemas"]["Parameter"][];
        };
        SessionListResponse: {
            sessions: components["schemas"]["SessionSummary"][];
        };
        SessionSummary: {
            sessionId: string;
            title: string;
            language: string;
            /** Format: date-time */
            lastTurnAt: string;
        };
        SessionResponse: {
            sessionId: string;
            uid: string;
            passId?: string | null;
            title: string;
            language: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastTurnAt: string;
            turns: components["schemas"]["TurnResponse"][];
        };
        ToolCallResponse: {
            name: string;
            /** Format: int32 */
            creditCost: number;
            cacheHit: boolean;
        };
        TurnResponse: {
            turnId: string;
            /** @description USER | ASSISTANT | TOOL */
            role: string;
            content: string;
            toolCalls: components["schemas"]["ToolCallResponse"][];
            /** Format: date-time */
            createdAt: string;
        };
        PassView: {
            passId: string;
            pack: string;
            /** Format: int32 */
            creditsInitial: number;
            /** Format: int32 */
            creditsRemaining: number;
            /** Format: int32 */
            chatTurnsInitial: number;
            /** Format: int32 */
            chatTurnsRemaining: number;
            purchasedAt: string;
            expiresAt: string;
            status: string;
        };
        PassesResponse: {
            passes: components["schemas"]["PassView"][];
        };
        DossiersResponse: {
            dossiers: components["schemas"]["SavedDossierView"][];
        };
        CreditEventView: {
            eventId: string;
            passId?: string | null;
            toolName: string;
            /** Format: int32 */
            cost: number;
            /** Format: int32 */
            balanceAfter: number;
            plateContext?: string | null;
            timestamp: string;
        };
        CreditHistoryResponse: {
            events: components["schemas"]["CreditEventView"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    sign: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UploadResponse"];
                };
            };
        };
    };
    invoke: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToolInvokeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ToolInvokeResponse"];
                };
            };
        };
    };
    portalSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortalRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PortalResponse"];
                };
            };
        };
    };
    checkout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CheckoutResponse"];
                };
            };
        };
    };
    rdw: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RdwLookupRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RdwVehicleSummary"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DossiersResponse"];
                };
            };
        };
    };
    save: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SavedDossierView"];
                };
            };
        };
    };
    chat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    chatStream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": Record<string, never>;
                };
            };
        };
    };
    getDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plate: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RdwVehicleDetail"];
                };
            };
        };
    };
    getMarktaanbod: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plate: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MarktaanbodResponse"];
                };
            };
        };
    };
    getKosten: {
        parameters: {
            query?: {
                province?: string;
            };
            header?: never;
            path: {
                plate: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Monthly cost breakdown */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MonthlyCosts"];
                };
            };
            /** @description Plate not in the RDW registry */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    deleteMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ToolSpec"][];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionListResponse"];
                };
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    list_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PassesResponse"];
                };
            };
        };
    };
    history: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CreditHistoryResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plate: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
